[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# SPA: redireciona qualquer rota para index.html
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# (opcional) config para dev local com Vite
[dev]
  command = "vite"
  port    = 5173
  targetPort = 5173
  framework = "vite"
