[build]
  command   = "npm run build"
  publish   = "build"
  functions = "netlify/functions"

# Proxy para as functions
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# SPA fallback (React Router)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]
  included_files = ["netlify/functions/**"]
