[build]
  command   = "npm run build"
  publish   = "build"
  functions = "netlify/functions"

# 1) Proxy das Netlify Functions (fica ANTES do fallback da SPA)
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# 2) Fallback da SPA (React Router)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[dev]
  command   = "npm start"
  port      = 3000
  targetPort = 3000
